version: "3.9"

services:
  support-bot:
    container_name: support-bot
    image: buildtheearth/support-bot
    ports:
      - "8890:8890"
    networks:
      - bot-network
    build: .
    environment:
        CONFIG_FILE: "/etc/buildtheearth/support-bot/config.ini"
    volumes:
      - "${CONFIG_FILE}:/etc/buildtheearth/support-bot/config.ini"
        
networks:
  bot-network:
    external: true
